runtime: python39  # Replace with the desired Python version
# entrypoint: gunicorn -b :$PORT app:app

# instance_class: F2

# automatic_scaling:
#   target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
